// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

/// @title MockZKVerifier
/// @notice Simulates a Groth16 ZK-SNARK verifier for enrollment proofs.
/// @dev In production this would be a real Groth16 verifier generated by snarkjs/circom.
///      In our mock, a proof is "valid" if the pi_a[0] != 0 (non-zero proof format check).
///      The nullifier (public output) is stored to prevent double-use.
contract MockZKVerifier {
    // nullifierHash => used
    mapping(bytes32 => bool) public nullifierUsed;

    event ProofVerified(bytes32 indexed nullifierHash, address indexed prover);

    error ZKVerifier__InvalidProof();
    error ZKVerifier__NullifierAlreadyUsed(bytes32 nullifierHash);

    /// @notice Verifies a ZK enrollment proof.
    /// @param proof      The proof bytes (simulated: must be non-empty and start with 0x01..0xff).
    /// @param nullifierHash  Public output: unique per (student, challenge) pair. Prevents reuse.
    /// @param merkleRoot The claimed Merkle root of enrolled students.
    /// @param expectedRoot The on-chain known Merkle root to compare against.
    /// @return valid True if the proof is accepted.
    function verifyProof(
        bytes calldata proof,
        bytes32 nullifierHash,
        bytes32 merkleRoot,
        bytes32 expectedRoot
    ) external returns (bool valid) {
        // Root must match
        if (merkleRoot != expectedRoot) revert ZKVerifier__InvalidProof();
        // Proof must be non-empty (simulated validity check)
        if (proof.length == 0 || proof[0] == 0x00) revert ZKVerifier__InvalidProof();
        // Nullifier must not be reused
        if (nullifierUsed[nullifierHash]) revert ZKVerifier__NullifierAlreadyUsed(nullifierHash);

        nullifierUsed[nullifierHash] = true;
        emit ProofVerified(nullifierHash, msg.sender);
        return true;
    }
}
